# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 802d3e615646c43b087f9ea17abd2d8513a6a51a3c7a47c16ab06409abe236df86891008781b89dccdc15aec70aab842f8aa8a790c639de19bf8aa579d94b94c

test:
  secret_key_base: 920df77525c761c07ace08b6116c41f342ddb4bfceb30eb51ed4b50d64315d88e2888447b164e285ccec0d35bac3ecf8952fb184af96e9695ed8138757c7c84c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
