default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: moma_development
  host: localhost
  username: palopiie
  password:

test:
  <<: *default
  database: moma_test

production:
  <<: *default
  database: moma_production
  username: palopiie
  password:
